### ISSUE TITLE
How do you import & use ReverberatorEstimator ?

### ISSUE THREAD

**Issue by cerkut** [VoggLyster/ReverberatorEstimator#1]
I need to add 

`import sys`
` sys.path.insert(0, os.path.abspath('../ReverberatorEstimator'))`
` from ReverberatorEstimator import layers, loss`

which works, but where is the models.py?

**Comment by VoggLyster** [comment]
oh, some old code got through the quick review. I need to remove the models.py from import. It contains nothing of use.
